DispatchSystem/Areas/Admin/Controllers/DispatchCountSummaryController.cs
using Dispatch_System.Controllers;
using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;
using System.Data;
using System.Data.SqlClient;

namespace Dispatch_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DispatchCountSummaryController : BaseController<ResponseModel<MDA_Status>>
    {
        public IActionResult Index()
        {
            var list = new List<SelectListItem_Custom>();

            CommonViewModel.Obj = new MDA_Status();

            List<OracleParameter> oParams = new List<OracleParameter>();

            oParams.Add(new OracleParameter("P_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
            oParams.Add(new OracleParameter("P_ISACTIVE", OracleDbType.Varchar2) { Value = "Y" });
            oParams.Add(new OracleParameter("P_PLANT_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
            oParams.Add(new OracleParameter("P_USER_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.USER_ID) });
            oParams.Add(new OracleParameter("P_ROLE_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.ROLE_ID) });
            oParams.Add(new OracleParameter("P_MENU_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.MENU_ID) });

            var dt = DataContext.ExecuteStoredProcedure_DataTable("PC_PLANT_GET", oParams, true);

            if (dt != null && dt.Rows.Count > 0)
            {
                CommonViewModel.Obj.PlantId = Common.Get_Session_Int(SessionKey.PLANT_ID);
                CommonViewModel.Obj.PlantName = dt.Rows[0]["NAME"] != DBNull.Value ? Convert.ToString(dt.Rows[0]["NAME"]) : "";
            }

            return View(CommonViewModel);
        }


        public ActionResult GetData_DispatchCountSummary(JqueryDatatableParam param)
        {
            string MdaNo = HttpContext.Request.Query["MdaNo"];
            string FromDate = HttpContext.Request.Query["FromDate"];
            string ToDate = HttpContext.Request.Query["ToDate"];
            string Type = HttpContext.Request.Query["Type"];

            List<MDA_Status> result = new List<MDA_Status>();

            List<OracleParameter> oParams = new List<OracleParameter>();

            oParams.Add(new OracleParameter("P_MDA_NO", OracleDbType.Varchar2) { Value = MdaNo });
            oParams.Add(new OracleParameter("P_FROM_DATE", OracleDbType.Varchar2) { Value = FromDate });
            oParams.Add(new OracleParameter("P_TO_DATE", OracleDbType.Varchar2) { Value = ToDate });
            //oParams.Add(new OracleParameter("P_SEARCH_TERM", OracleDbType.Varchar2) { Value = param.sSearch ?? "" });
            oParams.Add(new OracleParameter("P_DISPLAY_LENGTH", OracleDbType.Int64) { Value = param.iDisplayLength });
            oParams.Add(new OracleParameter("P_DISPLAY_START", OracleDbType.Int64) { Value = param.iDisplayStart });
            oParams.Add(new OracleParameter("P_PLANT_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
            oParams.Add(new OracleParameter("P_USER_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.USER_ID) });
            oParams.Add(new OracleParameter("P_ROLE_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.ROLE_ID) });
            oParams.Add(new OracleParameter("P_MENU_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.MENU_ID) });

            var dt = DataContext.ExecuteStoredProcedure_DataTable("PC_Dispatch_Count_Summary_REPORT", oParams, true);

            if (dt != null && dt.Rows.Count > 0)
            {
                foreach (DataRow dr in dt.Rows)
                    result.Add(new MDA_Status
                    {
                        MDANo = dr["MDA_NO"] != DBNull.Value ? Convert.ToString(dr["MDA_NO"]) : "",
                        MDAReceiveDate = dr["MDA_DATE"] != DBNull.Value ? Convert.ToString(dr["MDA_DATE"]) : "",
                        TruckNo = dr["TRUCK_NO"] != DBNull.Value ? Convert.ToString(dr["TRUCK_NO"]) : "",
                        MDAQty = dr["MDA_SHIPPER_QTY"] != DBNull.Value ? Convert.ToInt64(dr["MDA_SHIPPER_QTY"]) : 0,
                        DispatchedQtyKL = dr["MDA_BOTTLE_QTY"] != DBNull.Value ? Convert.ToInt64(dr["MDA_BOTTLE_QTY"]) : 0,
                        SKUCode = dr["PRODUCT_SKU_CODE"] != DBNull.Value ? Convert.ToString(dr["PRODUCT_SKU_CODE"]) : "",
                        SkuDesc = dr["PRODUT_SKU_DESC"] != DBNull.Value ? Convert.ToString(dr["PRODUT_SKU_DESC"]) : "",
                        Destination = dr["DESTINATION"] != DBNull.Value ? Convert.ToString(dr["DESTINATION"]) : "",
                    });
            }

            return Json(new
            {
                param.sEcho,
                iTotalRecords = result.Count(),
                iTotalDisplayRecords = dt != null && dt.Rows.Count > 0 ? Convert.ToInt32(dt.Rows[0]["COUNT_ROW"]?.ToString()) : 0,
                aaData = result
            });

        }

        [HttpGet]
        public IActionResult GetData(string Mda_No, string From_Date, string To_Date, bool withDetail = false, bool isPrint = false)
        {
            (string PageTitle_Primary, string PageTitle_Secondary) = ("", "");

            var result = new List<MDA_Status>();

            DataSet ds = new DataSet();

            try
            {
                var oParams = new List<OracleParameter>();

                oParams.Add(new OracleParameter("P_MDA_NO", OracleDbType.Varchar2) { Value = Mda_No ?? "" });
                oParams.Add(new OracleParameter("P_FROM_DATE", OracleDbType.Varchar2) { Value = From_Date ?? "" });
                oParams.Add(new OracleParameter("P_TO_DATE", OracleDbType.Varchar2) { Value = To_Date ?? "" });
                oParams.Add(new OracleParameter("P_PLANT_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
                oParams.Add(new OracleParameter("P_PAGE_TITLE", OracleDbType.RefCursor) { Direction = ParameterDirection.Output });
                oParams.Add(new OracleParameter("P_RESULT", OracleDbType.RefCursor) { Direction = ParameterDirection.Output });

                ds = DataContext.ExecuteStoredProcedure_DataSet("PC_Dispatch_Count_Summary_REPORT_NEW", oParams);

                if (ds != null && ds.Tables.Count > 1 && ds.Tables[1].Rows.Count > 0)
                {
                    foreach (DataRow dr in ds.Tables[1].Rows)
                        result.Add(new MDA_Status
                        {
                            //MDANo = dr["MDA_NO"] != DBNull.Value ? Convert.ToString(dr["MDA_NO"]) : "",
                            //MDAReceiveDate = dr["MDA_DATE"] != DBNull.Value ? Convert.ToString(dr["MDA_DATE"]) : "",
                            //TruckNo = dr["TRUCK_NO"] != DBNull.Value ? Convert.ToString(dr["TRUCK_NO"]) : "",
                            //MDAQty = dr["MDA_SHIPPER_QTY"] != DBNull.Value ? Convert.ToInt64(dr["MDA_SHIPPER_QTY"]) : 0,
                            //DispatchedQtyKL = dr["MDA_BOTTLE_QTY"] != DBNull.Value ? Convert.ToInt64(dr["MDA_BOTTLE_QTY"]) : 0,
                            //SKUCode = dr["PRODUCT_SKU_CODE"] != DBNull.Value ? Convert.ToString(dr["PRODUCT_SKU_CODE"]) : "",
                            //SkuDesc = dr["PRODUT_SKU_DESC"] != DBNull.Value ? Convert.ToString(dr["PRODUT_SKU_DESC"]) : "",
                            //Destination = dr["DESTINATION"] != DBNull.Value ? Convert.ToString(dr["DESTINATION"]) : "",
                            SrNo = dr["SR_NO"] != DBNull.Value ? Convert.ToString(dr["SR_NO"]) : "",
                            MDAReceiveDate = dr["GATE_OUT_DT"] != DBNull.Value ? Convert.ToString(dr["GATE_OUT_DT"]) : "",
                            TruckNo = dr["COUNT_TRUCK"] != DBNull.Value ? Convert.ToString(dr["COUNT_TRUCK"]) : "",
                            MDANo = dr["COUNT_MDA"] != DBNull.Value ? Convert.ToString(dr["COUNT_MDA"]) : "",
                            TotalShipperQTY = dr["SHIPPER_QTY"] != DBNull.Value ? Convert.ToInt64(dr["SHIPPER_QTY"]) : 0,
                            DispatchedQtyKL = dr["BOTTLE_QTY"] != DBNull.Value ? Convert.ToInt64(dr["BOTTLE_QTY"]) : 0,
                            //PlantName = dr["PLANT_NAME"] != DBNull.Value ? Convert.ToString(dr["PLANT_NAME"]) : "",
                            SkuDesc = dr["PRODUCT_NAME"] != DBNull.Value ? Convert.ToString(dr["PRODUCT_NAME"]) : ""
                        });
                }
            }
            catch (Exception ex) { LogService.LogInsert(GetCurrentAction(), "", ex); }

            PageTitle_Primary = (ds != null && ds.Tables.Count > 0 && ds.Tables[0] != null && ds.Tables[0].Rows.Count > 0
                                && ds.Tables[0].Rows[0]["PLANT_NAME"] != DBNull.Value) ? Convert.ToString(ds.Tables[0].Rows[0]["PLANT_NAME"]) : "";

            if (!string.IsNullOrEmpty(Mda_No))
                PageTitle_Secondary = "Mda No. : " + Mda_No.ToUpper();

            if (!string.IsNullOrEmpty(From_Date))
                PageTitle_Secondary += $"{(!string.IsNullOrEmpty(PageTitle_Secondary) ? " and " : "")}From Date : {From_Date.ToUpper()}";

            if (!string.IsNullOrEmpty(To_Date))
                PageTitle_Secondary += $"{(!string.IsNullOrEmpty(PageTitle_Secondary) ? " and " : "")}To Date : {To_Date.ToUpper()}";

            dynamic objFilter = new { Mda_No = Mda_No, From_Date = From_Date, To_Date = To_Date };

            if (isPrint == true)
                return View("_Partial_GetData", (PageTitle_Primary, PageTitle_Secondary, objFilter, result, withDetail, isPrint));
            else
                return PartialView("_Partial_GetData", (PageTitle_Primary, PageTitle_Secondary, objFilter, result, withDetail, isPrint));
        }
    }
}

DispatchSystem/Areas/Admin/Views/DispatchCountSummary/Index.cshtml
@model ResponseModel<MDA_Status>

@{
    ViewData["Title"] = "Dispatch Count Summary View";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var Url_RootToController = Url.Content("~/") + ViewContext.RouteData.Values["area"].ToString() + "/" + ViewContext.RouteData.Values["Controller"].ToString();
}


<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">MDA Dispatch Count Summary Report</h1>
            </div>

        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="card card-primary card-outline">

            <div class="card-body">

                <div class="panel-divider">
                    <span>Search</span>
                    <div class="row no-gutters p-0 m-0">
                        <div class="col-12 row no-gutters">
                            <div class="form-group col-md-3 mx-3">
                                <label class="col-form-label" style="align-content:start">Plant</label>
                                <input type="hidden" class="form-control form-control-sm" id="PlantId" value="@Model.Obj.PlantId">
                                <input type="text" class="form-control form-control-sm" id="PlantName" value="@Model.Obj.PlantName" autocomplete="off" readonly>
                            </div>
                            <div class="form-group col-md-3 mx-3">
                                <label class="col-form-label" style="align-content:start">MDA No</label>
                                <input type="text" class="form-control form-control-sm" id="MDA_No" autocomplete="off">
                            </div>
                            <div class="form-group col-md-2 mx-3">
                                <label class="col-form-label" style="align-content:start">Date From</label>
                                <input type="text" class="form-control form-control-sm datepicker" id="FromDate" data-max="@DateTime.Now.ToString("dd/MM/yyyy")" autocomplete="off">
                            </div>
                            <div class="form-group col-md-2 mx-3">
                                <label class="col-form-label" style="align-content:start">Date To</label>
                                <input type="text" class="form-control form-control-sm datepicker" id="ToDate" data-max="@DateTime.Now.ToString("dd/MM/yyyy")" autocomplete="off">
                            </div>
                        </div>

                        @*<div class="col-12 no-gutters my-3">
                            <div class="form-group mx-3 text-center">
                                <label class="col-form-label text-right" style="align-content:start">&nbsp;</label>

                                <button type="button" class="btn btn-info btn-md pull-right mr-2" onclick="fnLoadTableData()"> Search </button>
                                <button type="button" class="btn btn-danger btn-md pull-right mr-2" onclick="fnClear()"> Clear </button>
                            </div>
                        </div>*@

                        <div class="col-12 no-gutters my-3">
                            <div class="form-group mx-3 text-center">
                                <label class="col-form-label text-right" style="align-content:start">&nbsp;</label>

                                <button type="button" class="btn btn-info btn-md pull-right mr-2" onclick="fnExecute_Report(false)"> Search </button>
                                <button type="button" class="btn btn-danger btn-md pull-right mr-2" onclick="fnClear()"> Clear </button>
                                <button type="button" class="btn btn-primary btn-md pull-right mr-2" onclick="fnExecute_Report(true)"> Print </button>
                                <button type="button" class="btn btn-success btn-md pull-right mr-2" id="btnExport"> Export </button>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="panel-divider">
                    <span>Details</span>
                    <div class="row no-gooters">
                        <div class="col-12 card card-primary p-0 m-0 shadow-none" style="margin: 0rem !important;">
                            <div class="card-body py-1 px-0" id="div_DataTable"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



@section Scripts{

    <script type="text/javascript">

        function fnClear() {
            $('#MDA_No').val("");
            $('#FromDate').val("");
            $('#ToDate').val("");
            $('#div_DataTable').html('');
        }

        $(function () { });

        $("#btnExport").click(function () {
            $("#tblDispatchCounty").table2excel({
                filename: "DispatchCountySummary.xls"
            });
            return false;
        });

        function fnExecute_Report($isPrint) {

            $('#div_DataTable').html('');

            var FromDate = $('#FromDate').val();
            var ToDate = $('#ToDate').val();
            var MdaNo = $('#MDA_No').val();

            // if ((typeof Truck_No != 'undefined' && Truck_No != null && Truck_No.length > 0)
            //     || (typeof FromDate != 'undefined' && FromDate != null && FromDate.length > 0)
            //     || (typeof ToDate != 'undefined' && ToDate != null && ToDate.length > 0)
            // ) {

            var $url = '@Url.Action("GetData", "DispatchCountSummary", new { area = "Admin" })?From_Date=' + FromDate + '&To_Date=' + ToDate + '&Mda_No=' + MdaNo + '&isPrint=' + $isPrint;

            if ($isPrint == true) {
                var printWindow = window.open($url, '_blank');

                if (printWindow) {
                    printWindow.onload = function () {
                        printWindow.print();
                    };
                }
            }
            else {

                ShowLoader(true);

                $.ajax({
                    type: "GET",
                    url: $url,
                    data: null,
                    contentType: "application/json; charset=utf-8",
                    dataType: "html",
                    success: function (response) {

                        setTimeout(function () {

                            $('#div_DataTable').html(response);

                            try { fnLoadCommonTable('#div_DataTable .table_Common'); } catch { }

                            ShowLoader(false);

                        }, 1000);

                    },
                    failure: function (response) {
                        ShowLoader(false);
                        CommonAlert_Error(null);
                    },
                    error: function (response) {
                        ShowLoader(false);
                        CommonAlert_Error(null);
                    }
                });
            }
            // }
            // else
            //ShowLoader(false);
        }

        //function fnLoadTableData() {
        //    if ($.fn.DataTable.isDataTable('#dataTable_PoDetails')) {
        //        $('#dataTable_PoDetails').DataTable().destroy();
        //    }

        //    var subHeading = "";

        //    if ($('#MDA_No').val() != null && $('#MDA_No').val() != '') {
        //        subHeading = 'MDA No: ' + $('#MDA_No').val();
        //    }

        //    if ($('#FromDate').val() != null && $('#FromDate').val() != '') {
        //        subHeading = 'Form Date: ' + $('#FromDate').val() + ' To Date: ' + $('#ToDate').val();
        //    }

        //    dataTableMain = $("#dataTable_PoDetails")
        //        .DataTable({
        //            "destroy": true,
        //            "pageLength": "All", "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
        //            "sAjaxSource": "@Url_RootToController/GetData_DispatchCountSummary",
        //            "bServerSide": true,
        //            "bProcessing": true,
        //            "bSearchable": true,
        //            "scrollX": true,
        //            "order": [[0, 'asc']],
        //            "language": { "emptyTable": "No record found.", "processing": '<i class="fa fa-spinner fa-spin fa-3x fa-fw" style="color:#2a2b2b;"></i><span class="sr-only">Loading...</span> ' },
        //            "fnServerParams": function (aoData) {
        //                aoData.push({ "name": "MdaNo", "value": "" + $('#MDA_No').val() });
        //                aoData.push({ "name": "FromDate", "value": "" + $('#FromDate').val() });
        //                aoData.push({ "name": "ToDate", "value": "" + $('#ToDate').val() });
        //                aoData.push({ "name": "Type", "value": "" });
        //            },
        //            "columns": [
        //                { "title": "MDA No.", "data": "mdaNo", "autoWidth": true, "searchable": true },
        //                { "title": "MDA Date", "data": "mdaReceiveDate", "autoWidth": true, "searchable": true },
        //                { "title": "Truck No", "data": "truckNo", "autoWidth": true, "searchable": true },
        //                { "title": "MDA Qty (Shippers)", "data": "mdaQty", "autoWidth": true, "searchable": true, "className": "dt-center" },
        //                { "title": "MDA Qty(Bottle)", "data": "dispatchedQtyKL", "autoWidth": true, "searchable": true, "className": "dt-center" },
        //                { "title": "SKU Code", "data": "skuCode", "autoWidth": true, "searchable": true, "className": "dt-center" },
        //                { "title": "SKU Desc", "data": "skuDesc", "autoWidth": true, "searchable": true },
        //                { "title": "Destination", "data": "destination", "autoWidth": true, "searchable": true },
        //            ],
        //            "dom": "<'row'<'col-sm-6 mb-3'B>>" +
        //                "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
        //                "<'row'<'col-sm-12'tr>>" +
        //                "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
        //            "buttons": [
        //                //     {
        //                //     extend: "csv",
        //                //     className: "btn-flat btn-info mx-2 px-3",
        //                //     titleAttr: 'Export in CSV',
        //                //     text: 'CSV',
        //                //     filename: 'Dispatch Count Summary List',
        //                //     init: function (api, node, config) { $(node).removeClass('btn-default') }
        //                // },
        //                // {
        //                //     extend: "excel",
        //                //     className: "btn-flat btn-success mx-2 px-3",
        //                //     titleAttr: 'Export in Excel',
        //                //     text: 'Excel',
        //                //     filename: 'Dispatch Count Summary List',
        //                //     init: function (api, node, config) { $(node).removeClass('btn-default') }
        //                // },
        //                {
        //                    extend: "pdfHtml5",
        //                    className: "btn-flat btn-danger mx-2 px-3",
        //                    titleAttr: 'Export in PDF',
        //                    text: 'PDF',
        //                    pageSize: 'LEGAL',
        //                    filename: 'Dispatch Count Summary Report',
        //                    //columnAlignments: array(
        //                    //    'MDA Qty (Shippers)'  => 'center',
        //                    //    'MDA Qty(Bottle)' => 'center',
        //                    //    'SKU Code'  => 'center',
        //                    //),
        //                    exportOptions: {
        //                        modifier: {
        //                            page: 'all' // Export all pages
        //                        }
        //                    },
        //                    init: function (api, node, config) { $(node).removeClass('btn-default') },
        //                    customize: function (doc) {
        //                        doc.defaultStyle.fontSize = 9;
        //                        doc.pageMargins = [5, 10, 5, 10]; // Adjust margins
        //                        doc.pageOrientation = 'Portrait'; // Set orientation
        //                        doc.content.splice(1, 0, {
        //                            text: subHeading,
        //                            style: 'subheader'
        //                        });
        //                        doc.styles.subheader = {
        //                            fontSize: 12,
        //                            italics: true,
        //                            margin: [10, 0, 0, 10]
        //                        };
        //                        //doc.content[0].table.widths = ['*', '*', '*', '*', '*' ];
        //                        // Add more customization options as needed
        //                    }
        //                }]
        //        });

        //}
    </script>
}

DispatchSystem/Areas/Admin/Views/DispatchCountSummary/_Partial_GetData.cshtml
@using System.Globalization;
@model (string PageTitle_Primary, string PageTitle_Secondary, dynamic objFilter, List<MDA_Status> List, bool withDetail, bool isPrint)

@if (Model.isPrint == true)
{
    ViewData["Title"] = "MDA Dispatch Count Summary Report";
    Layout = "~/Views/Shared/_Layout_Print.cshtml";
}

<div class="row col-12 mb-3">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12" style="text-align:center;">
                <h2 class="font-weight-bold">@(!string.IsNullOrEmpty(Model.PageTitle_Primary) ? Model.PageTitle_Primary : "IFFCO NANO FERTILIZER PLANT - KALOL") </h2>
            </div>
            <br />
            <div class="col-sm-12" style="text-align:center;">

                @if (!string.IsNullOrEmpty(Model.PageTitle_Secondary))
                {
                    <h5 class="font-weight-bold">
                        MDA Dispatch Count Summary : @Model.PageTitle_Secondary
                    </h5>
                }
                else
                {
                    <h4 class="font-weight-bold">MDA Dispatch Count Summary Detail </h4>
                }
            </div>
            <br />
            <div class="col-sm-12 @(Model.isPrint == true ? "":"d-none")" style="text-align:right;">
                <h5 class="font-weight-bold"><b>Printed on : @DateTime.Now.ToString("dd/MM/yyyy hh:mm tt").Replace("-", "/")</b></h5>
            </div>
            <br />
        </div>
    </div>
</div>

<div class="row col-12 mt-5 text-center table-responsive">

    @* <table id="table_Common" class="table table-bordered w-100 divDetail @((Model.withDetail == true) ? "" : "d-none")"> *@
    <table class="table table-bordered w-100 table_Common divDetail" id="tblDispatchCounty">
        <thead>
            <tr>
                <th width="0%">#</th>
                <th width="10%">Dispatch Date</th>
                <th width="10%">No of Truck</th>
                <th width="10%">No of MDA</th>
                <th width="10%">No of Shipper</th>
                <th width="10%">No of Bottles</th>
                <th>Product</th>
                <th hidden>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.List != null && Model.List.Count() > 0)
            {
                @foreach (var item in Model.List.OrderBy(x => x.SrNo).ToList())
                {
                    <tr>
                        <td>@item.SrNo</td>
                        <td>@item.MDAReceiveDate</td>
                        <td>@item.TruckNo</td>
                        <td>@item.MDANo</td>
                        <td>@item.TotalShipperQTY</td>
                        <td>@item.DispatchedQtyKL</td>
                        <td>@item.SkuDesc</td>
                        <td hidden>&nbsp;</td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="7"><span class="w-100">No any records found.</span></td></tr>
            }
        </tbody>

    </table>

</div>