DispatchSystem/Areas/Dispatch/Controllers/RmGateInController.cs
using Dispatch_System.Controllers;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Oracle.ManagedDataAccess.Client;
using System.Data;
using System.Globalization;

namespace Dispatch_System.Areas.Dispatch.Controllers
{
    [Area("Dispatch")]
    public class RmGateInController : BaseController<ResponseModel<GateIn>>
    {
        #region Loading

        public IActionResult Index()
        {
            var list = new List<SelectListItem_Custom>();

            var oParams = new List<MySqlParameter>();

            try
            {
                list.Insert(0, new SelectListItem_Custom("", "-- Select --", "DRVIDPROOF"));

                oParams.Add(new MySqlParameter("P_LOV_COLUMN", MySqlDbType.VarChar) { Value = "DRVIDPROOF" });
                oParams.Add(new MySqlParameter("P_ISACTIVE", MySqlDbType.VarChar) { Value = "Y" });
                oParams.Add(new MySqlParameter("P_PLANT_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
                oParams.Add(new MySqlParameter("P_USER_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.USER_ID) });
                oParams.Add(new MySqlParameter("P_ROLE_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.ROLE_ID) });
                oParams.Add(new MySqlParameter("P_MENU_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.MENU_ID) });

                var dt = DataContext.ExecuteStoredProcedure_DataTable_SQL("PC_LOV_GET", oParams, false);

                if (dt != null && dt.Rows.Count > 0)
                    foreach (DataRow dr in dt.Rows)
                        list.Add(new SelectListItem_Custom(Convert.ToString(dr["LOV_CODE"]), Convert.ToString(dr["LOV_DESC"]), "DRVIDPROOF"));

            }
            catch (Exception ex) { LogService.LogInsert(GetCurrentAction(), "", ex); }


            try
            {
                //list.Insert(0, new SelectListItem_Custom("0", "-- Select --", "INWARDTYPE"));

                oParams[0] = new MySqlParameter("P_ID", MySqlDbType.Int64) { Value = 0 };

                var dt = DataContext.ExecuteStoredProcedure_DataTable_SQL("PC_INWARD_GET", oParams, false);

                if (dt != null && dt.Rows.Count > 0)
                    foreach (DataRow dr in dt.Rows)
                        list.Add(new SelectListItem_Custom(Convert.ToString(dr["ID"]), Convert.ToString(dr["INWARD_TYPE"]), "INWARDTYPE"));

            }
            catch (Exception ex) { LogService.LogInsert(GetCurrentAction(), "", ex); }


            CommonViewModel.SelectListItems = list;

            return View(CommonViewModel);
        }

        #endregion

        #region Methods

        [HttpGet]
        public IActionResult GetPO(string type, string searchTerm)
        {
            var list = new List<PO>();

            try
            {
                List<MySqlParameter> oParams = new List<MySqlParameter>();

                //oParams.Add(new MySqlParameter("P_ID", MySqlDbType.Int64) { Value = 0 });

                //oParams.Add(new MySqlParameter("P_VEHICLE_NO", MySqlDbType.VarChar) { Value = "" });
                //oParams.Add(new MySqlParameter("P_INWARD_SYS_ID", MySqlDbType.Int64) { Value = Inward_Sys_Id });
                //oParams.Add(new MySqlParameter("P_RESULT", MySqlDbType.RefCursor) { Direction = ParameterDirection.Output });
                //oParams.Add(new MySqlParameter("P_DTLS", MySqlDbType.RefCursor) { Direction = ParameterDirection.Output });
                oParams.Add(new MySqlParameter("P_SearchTerm", MySqlDbType.VarChar) { Value = (!string.IsNullOrEmpty(searchTerm)) ? searchTerm : "" });
                oParams.Add(new MySqlParameter("P_PLANT_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });

                DataTable dt = DataContext.ExecuteStoredProcedure_DataTable_SQL("PC_GATE_IN_PO_LIST", oParams);

                if (dt != null && dt.Rows.Count > 0)
                    foreach (DataRow dr in dt.Rows)
                        //if ((dr["PO_SYS_ID"] != DBNull.Value ? Convert.ToInt64(dr["PO_SYS_ID"]) : 0) <= 0)
                        list.Add(new PO()
                        {
                            Id = dr["PO_SYS_ID"] != DBNull.Value ? Convert.ToInt64(dr["PO_SYS_ID"]) : 0,
                            PoNo = dr["PO_NO"] != DBNull.Value ? Convert.ToString(dr["PO_NO"]) : "",
                            PoDate_Text = dr["PO_DATE"] != DBNull.Value ? DateTime.ParseExact(Convert.ToString(dr["PO_DATE"]), "dd-MM-yyyy HH:mm:ss", CultureInfo.InvariantCulture).ToString("dd/MM/yyyy").Replace("-", "/") : "",
                            VendorId = dr["VENDOR_SYS_ID"] != DBNull.Value ? Convert.ToInt64(dr["VENDOR_SYS_ID"]) : 0,
                            VendorName = dr["ORGANIZATION_NAME"] != DBNull.Value ? Convert.ToString(dr["ORGANIZATION_NAME"]) : "",
                            SiteName = dr["VENDOR_SITE"] != DBNull.Value ? Convert.ToString(dr["VENDOR_SITE"]) : "",
                            CostCenter = dr["COST_CENTER"] != DBNull.Value ? Convert.ToInt64(dr["COST_CENTER"]) : 0,
                            PoDesc = dr["PO_DESCCRIPTION"] != DBNull.Value ? Convert.ToString(dr["PO_DESCCRIPTION"]) : "",
                            TransId = dr["TRANS_SYS_ID"] != DBNull.Value ? Convert.ToInt64(dr["TRANS_SYS_ID"]) : 0,
                            TruckNo = dr["TRUCK_NO"] != DBNull.Value ? Convert.ToString(dr["TRUCK_NO"]) : "",
                            Transporter_Code = dr["tptr_cd"] != DBNull.Value ? Convert.ToString(dr["tptr_cd"]) : "",
                            Transporter_Name = dr["TPTR_NAME"] != DBNull.Value ? Convert.ToString(dr["TPTR_NAME"]) : "",
                            Is_PO_Manually = dr["IS_PO_MANUAL"] != DBNull.Value ? Convert.ToBoolean(dr["IS_PO_MANUAL"]) : false,
                            SiteId = dr["STATION_ID"] != DBNull.Value ? Convert.ToInt64(dr["STATION_ID"]) : 0,
                            PlantId = dr["PLANT_ID"] != DBNull.Value ? Convert.ToInt64(dr["PLANT_ID"]) : 0,
                            Plant_CD = dr["PLANT_CD"] != DBNull.Value ? Convert.ToString(dr["PLANT_CD"]) : "",
                        });

            }
            catch (Exception ex) { LogService.LogInsert(GetCurrentAction(), "", ex); }

            foreach (var item in list)
                if (!string.IsNullOrEmpty(item.PoDate_Text))
                    try { item.PoDate_Text = DateTime.ParseExact(item.PoDate_Text.Trim(), "dd/MM/yyyy", CultureInfo.InvariantCulture).ToString("dd/MM/yyyy").Replace("-", "/"); } catch { continue; }

            if (list != null && list.Count > 0)
                if (!string.IsNullOrEmpty(type) && type == "S" && list.Count == 1) return Json(list.FirstOrDefault());
                else return PartialView("_Partial_PO", list);
            else return Json(null);
            //return PartialView("_Partial_MDA", list);
        }

        [HttpGet]
        public IActionResult Partial_AddEditForm_PO(int Id)
        {
            var obj = new ResponseModel<PO>();

            List<SelectListItem_Custom> list = new List<SelectListItem_Custom>();

            list.Insert(0, new SelectListItem_Custom("", "-- Select Vendor --", "V"));

            List<MySqlParameter> oParams = new List<MySqlParameter>();

            oParams.Add(new MySqlParameter("P_ID", MySqlDbType.Int64) { Value = 0 });
            oParams.Add(new MySqlParameter("P_VENDOR_CODE", MySqlDbType.Int64) { Value = 0 });
            oParams.Add(new MySqlParameter("P_SEARCHTERM", MySqlDbType.VarChar) { Value = "" });
            oParams.Add(new MySqlParameter("P_ISACTIVE", MySqlDbType.VarChar) { Value = "Y" });
            oParams.Add(new MySqlParameter("P_PLANT_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
            oParams.Add(new MySqlParameter("P_USER_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.USER_ID) });
            oParams.Add(new MySqlParameter("P_ROLE_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.ROLE_ID) });
            oParams.Add(new MySqlParameter("P_MENU_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.MENU_ID) });
            //oParams.Add(new MySqlParameter("P_RESULT", MySqlDbType.RefCursor) { Direction = ParameterDirection.Output });
            //oParams.Add(new MySqlParameter("P_SITES", MySqlDbType.RefCursor) { Direction = ParameterDirection.Output });

            var dt = DataContext.ExecuteStoredProcedure_DataTable_SQL("PC_VENDOR_GET", oParams, false);

            if (dt != null && dt.Rows.Count > 0)
                foreach (DataRow row in dt.Rows)
                    list.Add(new SelectListItem_Custom(row["ID"].ToString(), row["Organization_Name"].ToString() + " -- " + row["VENDOR_SITE"].ToString(), row["VENDOR_SITE"].ToString(), "V"));

            oParams = new List<MySqlParameter>();

            oParams.Add(new MySqlParameter("P_LOV_COLUMN", MySqlDbType.VarChar) { Value = "UOM" });
            oParams.Add(new MySqlParameter("P_ISACTIVE", MySqlDbType.VarChar) { Value = "Y" });
            oParams.Add(new MySqlParameter("P_PLANT_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
            oParams.Add(new MySqlParameter("P_USER_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.USER_ID) });
            oParams.Add(new MySqlParameter("P_ROLE_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.ROLE_ID) });
            oParams.Add(new MySqlParameter("P_MENU_ID", MySqlDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.MENU_ID) });

            dt = DataContext.ExecuteStoredProcedure_DataTable_SQL("PC_LOV_GET", oParams, true);

            list.Insert(0, new SelectListItem_Custom("", "-- Select UOM --", "U"));

            if (dt != null && dt.Rows.Count > 0)
                foreach (DataRow row in dt.Rows)

DispatchSystem/Areas/Dispatch/Views/RmGateIn/_Partial_AddEditForm_PO.cshtml
@model ResponseModel<PO>
@{
	Layout = null;
	var IndexPageUrl = "/" + ViewContext.RouteData.Values["Area"].ToString() + "/" + ViewContext.RouteData.Values["Controller"].ToString() + "/Index";
}

<div class="col-12">
	<form id="formSave_PO" asp-area="Dispatch" asp-controller="RmGateIn" asp-action="Save_PO" method="post" class="form-horizontal" enctype="multipart/form-data">
		<div class="card card-primary card-outline">
			<div class="card-body @(Model.Obj.Id > 0 ? " pt-0 mt-0":"")">
				<input type="text" class="form-control d-none" name="Id" value="@Model.Obj.Id">

				<div class="row p-0 m-0 d-flex">
					<div class="col-12 tab-content p-0 m-0">

						<div id="tab_PO" class="tab-pane active row no-gutters p-0 m-0">
							<div class="col-12 card card-primary p-0 m-0 shadow-none mt-3">
								<div class="form-group row">
									<label for="PoNo" class="col-sm-1 col-form-label">PO/Invoice No <span style="color:red">*</span></label>
									<div class="col-sm-3">
										<input type="text" class="form-control form-control-sm" name="PoNo" value="@Model.Obj.PoNo" maxlength="50"
											   data-required data-msg="The PO/Invoice No field is required." autocomplete="off">
									</div>
								</div>
								<hr />
								<div class="form-group row">
									<label for="VendorId" class="col-sm-1 col-form-label" style="align-content:start">Vendor <span style="color:red">*</span></label>
									<div class="col-sm-3">
										<select id="VendorId" name="VendorId" class="form-control form-control-sm select2" style="width: 100%;" onchange="getVendorSite()">
											@if (Model != null && Model.SelectListItems != null)
											{
												foreach (var item in Model.SelectListItems.Where(x => x.Group == "V"))
												{
													<option value="@item.Value" data-vendorcode="@item.Value2">@item.Text</option>
												}
												@*<option value="other">Other</option>*@
											}
										</select>
									</div>
									<div class="col-sm-2">
										<button type="button" class="btn btn-info btn-md pull-right mr-2" onclick="fnClick_AddVendor()">
											<i class="fas fa-plus"></i> &nbsp; Add Vendor
										</button>
									</div>
									@*<label for="SelectedSiteName" class="col-sm-1 col-form-label" style="align-content:start">Vendor Site<span style="color:red">*</span></label>
									<div class="col-sm-3">
										<div class="input-group input-group-sm" id="divSiteId">
											<select id="SelectedSiteName" name="SelectedSiteName" class="form-control form-control-sm select2" style="width: 100%;">
												@if (Model != null && Model.SelectListItems != null)
												{
													foreach (var item in Model.SelectListItems.Where(x => x.Group == "N"))
													{
														<option value="@item.Value">@item.Text</option>
													}
												}
											</select>
										</div>
									</div>*@
								</div>
								<div class="form-group row d-none customVendor">
									<label for="VendorName" class="col-sm-1 col-form-label" style="align-content:start">New Vendor Name <span style="color:red">*</span></label>
									<div class="col-sm-3">
										<input type="text" class="form-control form-control-sm" id="VendorName" name="VendorName" autocomplete="off">
									</div>
									<div class="col-sm-2">
										&nbsp;
									</div>
									<label for="SiteName" class="col-sm-1 col-form-label" style="align-content:start">New Vendor Site Name <span style="color:red">*</span></label>
									<div class="col-sm-3">
										<input type="text" class="form-control form-control-sm" id="SiteName" name="SiteName" autocomplete="off">
									</div>
								</div>
								<div class="form-group row">
									<label for="PoDate" class="col-sm-1 col-form-label">PO/Invoice Date</label>
									<div class="col-sm-3">
										<input type="text" class="form-control form-control-sm datepicker" id="PoDate" name="PoDate"
											   data-value="@Model.Obj.PoDate_Text" value="@Model.Obj.PoDate?.ToString("dd/MM/yyyy").Replace("-", "/")" maxlength="50"
											   data-required data-msg="The PO/Invoice Date field is required." autocomplete="off">
									</div>

								</div>
								<div class="form-group row">
									<label for="PoDesc" class="col-sm-1 col-form-label">PO/Invoice Description <span style="color:red">*</span></label>
									<div class="col-sm-8">
										<input type="text" class="form-control form-control-sm" id="PoDesc" name="PoDesc" value="@Model.Obj.PoDesc" maxlength="50"
											   data-required data-msg="The PO/Invoice Desc field is required." autocomplete="off">
									</div>
								</div>

								<hr />
								<div class="form-group row">
									<label for="TransId" class="col-sm-1 col-form-label" style="align-content:start">Transporter <span style="color:red">*</span></label>
									<div class="col-sm-3">
										<select id="TransId" name="TransId" class="form-control form-control-sm select2" style="width: 100%;" >
											@if (Model != null && Model.SelectListItems != null)
											{
												foreach (var item in Model.SelectListItems.Where(x => x.Group == "T"))
												{
													<option value="@item.Value">@item.Text</option>
												}
												@*<option value="other">Other</option>*@
											}
										</select>
									</div>
									<div class="col-sm-2">
										<button type="button" class="btn btn-info btn-md pull-right mr-2" onclick="fnClick_AddTransporter()">
											<i class="fas fa-plus"></i> &nbsp; Add Transporter
										</button>
									</div>
									<label for="TruckNo" class="col-sm-1 col-form-label">Truck No. <span style="color:red">*</span></label>
									<div class="col-sm-3">
										<input type="text" class="form-control form-control-sm" id="TruckNo" name="TruckNo"
											   data-required data-msg="The Truck No. field is required." autocomplete="off">
									</div>
								</div>
								<div class="form-group row d-none customTransporter">
									<label for="TransId" class="col-sm-1 col-form-label" style="align-content:start">New Transporter Name <span style="color:red">*</span></label>
									<div class="col-sm-3">
										<input type="text" class="form-control form-control-sm" id="Transporter_Name" name="Transporter_Name" autocomplete="off">
									</div>
								</div>
								<hr />

								<div class="row mb-2">
									<div class="col-sm-6">
										<h5 class="m-0 text-left">Vendor PO/Invoice Details</h5>
									</div>
									<div class="col-sm-6">
										<div class="float-sm-right">
											@* @if (Common.IsAdmin())
											{ *@
											<button type="button" class="btn btn-info btn-md pull-right mr-2" onclick="fnAddRow()">
												<i class="fas fa-plus"></i> &nbsp; Add PO/Invoice Item
											</button>
											@* } *@
										</div>
									</div>
								</div>


								<div class="row no-gooters">
									<div class="col-md-12 my-1">
										<table id="table_PODtls" class="table table-bordered table-striped w-100">
											<thead>
												<tr>
													<th width="5%">Line No</th>
													<th>Line Description</th>
													<th width="15%">UOM</th>
													<th width="15%">Quantity</th>
													<th width="5%">Action</th>
												</tr>
											</thead>
											<tbody>
												<tr id="tr_ZX" class="d-none">
													<td><input type="text" class="form-control form-control-sm text-center" name="listPODtls[ZX].LineNo" maxlength="50" autocomplete="off" readonly></td>
													<td><input type="text" class="form-control form-control-sm" name="listPODtls[ZX].LineDesc" maxlength="50" autocomplete="off"></td>
													<td>
														<input type="text" class="form-control form-control-sm d-none" id="listPODtls[ZX]_UOM" name="listPODtls[ZX].UOM" autocomplete="off">

														<select class="form-control form-control-sm ddlUOM" onchange="fnChange_Select(this,'form#formSave_PO #table_PODtls tbody tr#tr_ZX input[name*=\'UOM\']')">
															@if (Model != null && Model.SelectListItems != null)
															{
																foreach (var item in Model.SelectListItems.Where(x => x.Group == "U"))
																{
																	<option value="@item.Value">@item.Text</option>
																}
															}
														</select>
													</td>
													<td><input type="text" class="form-control form-control-sm isNumberKey_Decimal" name="listPODtls[ZX].LineQty" maxlength="50" autocomplete="off"></td>
													<td>
														<div class="btn-group">
															<button type="button" class="btn btn-danger btn-sm btn-flat ml-2" data-toggle="tooltip" data-placement="top" title="Delete"
																	onclick="fnDelete_Row('ZX');">
																<i class="far fa-trash-alt"></i>
															</button>
														</div>
													</td>
												</tr>
											</tbody>
										</table>
									</div>

									<div class="clearfix"></div>
								</div>

								<div class="form-group row">
									<div class="col-12 card-footer text-center">
										<button type="button" class="btn btn-success" onclick="fnSubmitForm('formSave_PO');">Save</button>
										<button type="button" class="btn btn-danger" onclick="fnClose_Modal()">Cancel</button>
									</div>
								</div>

							</div>
						</div>

					</div>
				</div>

			</div>

		</div>

		<hr />
	</form>
</div>
@section Scripts{
	<script>
		$('#VendorId').select2({
			tags: true
		});
	</script>
}

DispatchSystem/Areas/Dispatch/Views/RmGateIn/_Partial_PO.cshtml
@model List<PO>

<div class="row col-12 mb-3">
    <button type="button" class="btn btn-info btn-flat px-3 mr-3" onclick="fnSelect_MDA()">Select</button>
    <button type="button" class="btn btn-danger btn-flat px-3 mr-3" onclick="fnClear_MDA()">Clear</button>
    <button type="button" class="btn btn-danger btn-flat px-3 mr-3" onclick="fnClose_Modal()">Close</button>
</div>

<div class="row col-12 w-100">
    <table id="table_Common" class="table table-bordered table-striped w-100">
        @*@if (((long)ViewBag.Inward_Sys_Id) == 126)*@
        @*{*@
        <thead>
            <tr>
                <th width="5%">Vehicle Number</th>
                <th width="5%">PO/Invoice Number</th>
                <th width="3%">Plant Code</th>
                <th width="10%">PO/Invoice Date</th>
                <th width="10%">Cost Center</th>
                <th>TPTR Code</th>
                <th>TPTR Name</th>
                <th>Vendor Name</th>
                <th>Site Name</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Count > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.TruckNo</td>
                        <td>@item.PoNo</td>
                        <td>@item.Plant_CD</td>
                        <td>@item.PoDate_Text</td>
                        <td>@item.CostCenter</td>
                        <td>@item.Transporter_Code</td>
                        <td>@item.Transporter_Name</td>
                        <td>@item.VendorName</td>
                        <td>@item.SiteName</td>
                    </tr>
                }
            }
        </tbody>
        @*}*@
    </table>
</div>