DispatchSystem/Areas/Admin/Controllers/ChangePasswordController.cs
using Dispatch_System.Controllers;
using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;

namespace Dispatch_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ChangePasswordController : BaseController<ResponseModel<ChangePassword>>
    {
		public IActionResult Index()
		{
			return View();
		}

        [HttpPost]
        public JsonResult Save(ChangePassword viewModel)
        {
            try
            {
                viewModel.CurrentPassword = Common.Encrypt(viewModel.CurrentPassword);
                viewModel.ConfirmPassword = Common.Encrypt(viewModel.ConfirmPassword);
                viewModel.NewPassword = Common.Encrypt(viewModel.NewPassword);

                List<OracleParameter> oParams = new List<OracleParameter>();

                oParams.Add(new OracleParameter("P_USER_NAME", OracleDbType.Varchar2) { Value = Common.Get_Session(SessionKey.USER_NAME) });
                oParams.Add(new OracleParameter("P_OLD_PASSWORD", OracleDbType.Varchar2) { Value = viewModel.CurrentPassword });
                oParams.Add(new OracleParameter("P_CONFIRM_PASSWORD", OracleDbType.Varchar2) { Value = viewModel.ConfirmPassword });
                oParams.Add(new OracleParameter("P_NEW_PASSWORD", OracleDbType.Varchar2) { Value = viewModel.NewPassword });
                oParams.Add(new OracleParameter("P_PLANT_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
                oParams.Add(new OracleParameter("P_USER_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.USER_ID) });
                oParams.Add(new OracleParameter("P_ROLE_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.ROLE_ID) });
                oParams.Add(new OracleParameter("P_MENU_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.MENU_ID) });

                var (IsSuccess, response, Id) = DataContext.ExecuteStoredProcedure("PC_CHANGEPASSWORD", oParams, true);

                CommonViewModel.IsConfirm = true;
                CommonViewModel.IsSuccess = IsSuccess;
                CommonViewModel.StatusCode = IsSuccess ? ResponseStatusCode.Success : ResponseStatusCode.Error;
                CommonViewModel.Message = response;

                CommonViewModel.RedirectURL = IsSuccess ? Url.Content("~/") + GetCurrentControllerUrl() + "/Index" : "";

            }
            catch (Exception ex)
            {
                LogService.LogInsert(GetCurrentAction(), "", ex);

                CommonViewModel.IsSuccess = false;
                CommonViewModel.StatusCode = ResponseStatusCode.Error;
                CommonViewModel.Message = ResponseStatusMessage.Error + " | " + ex.Message;
            }

            return Json(CommonViewModel);
        }
    }
}

DispatchSystem/Areas/Vendor/Controllers/ChangePasswordController.cs
using Dispatch_System.Controllers;
using Microsoft.AspNetCore.Mvc;
using Oracle.ManagedDataAccess.Client;

namespace Dispatch_System
{
	[Area("Vendor")]
	public class ChangePasswordController : BaseController<ResponseModel<VendorChangePassword>>
	{
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public JsonResult Save(ChangePassword viewModel)
		{
			try
			{
				viewModel.CurrentPassword = Common.Encrypt(viewModel.CurrentPassword);
				viewModel.NewPassword = Common.Encrypt(viewModel.NewPassword);
				viewModel.ConfirmPassword = Common.Encrypt(viewModel.ConfirmPassword);

				List<OracleParameter> oParams = new List<OracleParameter>();

				oParams.Add(new OracleParameter("P_VENDOR_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.USER_ID) });
				oParams.Add(new OracleParameter("P_OLD_PASSWORD", OracleDbType.Varchar2) { Value = viewModel.CurrentPassword });
				oParams.Add(new OracleParameter("P_CONFIRM_PASSWORD", OracleDbType.Varchar2) { Value = viewModel.ConfirmPassword });
				oParams.Add(new OracleParameter("P_NEW_PASSWORD", OracleDbType.Varchar2) { Value = viewModel.NewPassword });
				oParams.Add(new OracleParameter("P_PLANT_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.PLANT_ID) });
				oParams.Add(new OracleParameter("P_SITE_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.SITE_ID) });
				oParams.Add(new OracleParameter("P_ROLE_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.ROLE_ID) });
				oParams.Add(new OracleParameter("P_MENU_ID", OracleDbType.Int64) { Value = Common.Get_Session_Int(SessionKey.MENU_ID) });

				var (IsSuccess, response, Id) = DataContext.ExecuteStoredProcedure("PC_VENDOR_CHANGEPASSWORD", oParams, true);

				CommonViewModel.IsConfirm = true;
				CommonViewModel.IsSuccess = IsSuccess;
				CommonViewModel.StatusCode = IsSuccess ? ResponseStatusCode.Success : ResponseStatusCode.Error;
				CommonViewModel.Message = response;

				Common.Clear_Session();

				CommonViewModel.RedirectURL = IsSuccess ? Url.Content("~/") + "Home/VendorLogin" : "";
			}
			catch (Exception ex)
			{
				LogService.LogInsert(GetCurrentAction(), "", ex);

				CommonViewModel.IsSuccess = false;
				CommonViewModel.StatusCode = ResponseStatusCode.Error;
				CommonViewModel.Message = ResponseStatusMessage.Error + " | " + ex.Message;
			}

			return Json(CommonViewModel);
		}
	}
}

DispatchSystem/Areas/Vendor/Views/ChangePassword/Index.cshtml
@model ResponseModel<ChangePassword>
@{
    ViewData["Title"] = "Change Password";
}



@section Styles{
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <style>
        .eye-pass {
            position: absolute;
            margin-top: 15px;
            top: -4px;
            right: 0;
            margin-right: 35px;
            cursor: pointer;
        }

        input[type=password]::-ms-reveal,
        input[type=password]::-ms-clear {
            display: none;
        }
    </style>
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Change Password</h1>
            </div>           
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="col-12">
            <form id="formSave" asp-area="Vendor" asp-controller="ChangePassword" asp-action="Save" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="card card-primary card-outline">
                    <div class="card-body">
                        <div class="form-group row">
                            <label for="CurrentPassword" class="col-sm-2 col-form-label">Old Password<span style="color:red">*</span></label>
                            <div class="col-sm-4">
                                <input class="form-control" id="CurrentPassword" type="password" maxlength="50" name="CurrentPassword">
                                <i class="fa fa-eye eye-pass fa-eye-slash" onclick="fnChangeIcon('CurrentPassword','togglePassword1')" id="togglePassword1"></i>
                            </div>
                            <div class="col-sm-4">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="NewPassword" class="col-sm-2 col-form-label">New Password<span style="color:red">*</span></label>
                            <div class="col-sm-4">
                                <input class="form-control" id="NewPassword" type="password" maxlength="50" name="NewPassword">
                                <i class="fa fa-eye eye-pass fa-eye-slash" onclick="fnChangeIcon('NewPassword','togglePassword2')" id="togglePassword2"></i>
                            </div>
                            <label for="ConfirmPassword" class="col-sm-2 col-form-label">Confirm Password<span style="color:red">*</span></label>
                            <div class="col-sm-4">
                                <input class="form-control" id="ConfirmPassword" type="password" maxlength="50" name="ConfirmPassword">
                                <i class="fa fa-eye eye-pass fa-eye-slash" onclick="fnChangeIcon('ConfirmPassword','togglePassword3')" id="togglePassword"></i>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-success btnSubmit">Save</button>
                        <button type="button" class="btn btn-danger">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

@section Scripts{

    <script type="text/javascript">
        $(function () {

        });

        function fnChangeIcon($inputid, $fid) {

            const togglePassword = document.querySelector('#' + $fid);
            const password = document.querySelector('#' + $inputid);
            const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
            password.setAttribute('type', type);
            togglePassword.classList.toggle('fa-eye-slash');

        }

    </script>
}